### ISSUE TITLE
Feature request: support for PubSub snapshots

### ISSUE THREAD

**Issue by ostrokach** [GoogleCloudPlatform/kafka-pubsub-emulator#22]
The title says it all :). It would be great if the emulator supported PubSub snapshots, so that programs relying on snapshots could be used with the emulator.

**Comment by prodonjs** [comment]
Thanks for the submission. Seeking and Snapshotting went GA in February. Due to the low level of activity in this repository, we haven't allocated any resources to scope the changes necessary to support these features within the emulator. To the best of my knowledge, the [local emulator](https://cloud.google.com/pubsub/docs/emulator#known_limitations) that ships with gcloud does not support these features either.

What kind of use case do you have for the emulator? This project is essentially in maintenance mode at the moment but we'd love to hear more about your plans for using it to determine what kinds of resources we'd need to implement this feature. We're also happy to accept and review PRs.

**Comment by ostrokach** [comment]
Hi Jason, thanks for getting back to us!

Our current use-case is as follows: We are trying to put together some interactive Jupyter notebooks demonstrating stream data processing with Apache Beam. It would be nice for the users to be able to run those notebooks without having to create and authenticate with a GCP account. However, at the moment, the Beam Python SDK only supports Cloud PubSub as a source of streaming data, and some of the things that we would like to demonstrate in those notebooks require creating subscription snapshots.

The local `gcloud` emulator does not support subscriptions and, in my experience, has been buggy and unable to support even a basic Beam workflow. The Kafka-backed emulator has been working very well and passes a set of PubSub integration tests much faster than using PubSub itself. However, the lack of snapshot support is a bit limiting in our case. 

If we decided to serve those notebooks using something like [MyBinder](https://mybinder.org/), we could start a PubSub emulator as well as the Kafka and Zookeeper services behind the scenes, so the user would not have to worry about setting them up themselves.
