### ISSUE TITLE
Feature request: support for multiple instances of kafka-pubsub-emulator?

### ISSUE THREAD

**Issue by bull-edward-stewart** [GoogleCloudPlatform/kafka-pubsub-emulator#8]
Does the kafka-pubsub-emulator support running multiple instances?  We are thinking of running it containerized with multiple instances to support horizontal scaling.

Presumably we would hit issues with the message buffers getting out of sync between instances plus the subscription acknowledgement lists not matching?

**Comment by prodonjs** [comment]
As you suspect, running multiple instances of the emulator presents some challenges with respect to synchronizing the state of acknowledgments. Since each emulator effectively acts as a Kafka consumer and producer, the only way you could effectively run multiple instances of it without running into this issue would be if each emulator instance were assigned to different partitions from the Kafka topics being consumed. Currently, this is not something exposed through our configuration.

Depending on how many topics you use, another option would be to deploy multiple emulator instances, each responsible for handling particular topics, or for a particular operation (publish vs. pull). It doesn't give you full redundancy, but does allow you to distribute the load to multiple nodes. Since Kafka is already designed with horizontal scaling in mind, we decided not to implement our scaling model which would have required additional coordination services. At that point, we felt like were implementing much of what Kafka already provides.

Happy to discuss more about your particular use case or accept PRs.
